### ISSUE TITLE
Usage of keywords nearer to Smalltalk Syntax

### ISSUE THREAD

**Issue by phlprcks** [hpi-swa-teaching/Algernon-Launcher#100]
As a poweruser of AlgerNaN (and Squeak) I want to use Algernon keywords with the well known Smalltalk Syntax in order to have consistency between Algernon usage and coding.

Instead of  `browse Morph` I might want to type `Morph browse` in Algernon.

**Comment by matveysiva** [comment]
We have decided not to pursue this
