### ISSUE TITLE
Help Keyword doesn't list all available Help Entries.

### ISSUE THREAD

**Issue by sinnaj-r** [hpi-swa-teaching/Algernon-Launcher#110]
When I enter "help" it does not show all Help keywords.
If I set `isRelevantForAllStrings` for the HelpType to return true it works, but than the fuzzy matching for e.g. "help do" is broken. I'm no expert with the new FuzzyMatcher, but I think this should be an easy fix. 😃 

(We should also add a test for this behaviour)

**Comment by BenBals** [comment]
This should be fixed by #103.
