### ISSUE TITLE
Searching for class comments throws error

### ISSUE THREAD

**Issue by robertkirsten** [hpi-swa-teaching/Algernon-Launcher#113]
When I search for a class comment with the which-Keyword Algernon throws an error.

**Comment by BenBals** [comment]
Could you please document the issue properly
1. What are the steps to reproduce?
2. What is the error?
3. With which Squeak Version, Branch, OS...?
4. Any ideas why this is or when the regression was introduced?

**Comment by robertkirsten** [comment]
For me its enough just to search for any term as class comment like `which Quicksilver`.
The problem seems to be that Items are handed to ALGItem>>rankLessThan: which have no fuzzyRank although it is used in this method. 
Happens on development and other branches we currently work on since [commit 35a7e1d](https://github.com/hpi-swa-teaching/Algernon-Launcher/commit/35a7e1dcb17b4093b253aa2dc48062949d4b0acb), before it didn't happen to me.
Squeak version is 5.3 on macOS.

**Comment by BenBals** [comment]
Thank you very much. Will look into it after #103 gets merged.
