### ISSUE TITLE
rename hotwords to keywords in Wiki and update it with new keywords (after merging #50)

### ISSUE THREAD

**Issue by phlprcks** [hpi-swa-teaching/Algernon-Launcher#122]
Once the customer has approved the implementation of #50 we need to update the keywords in the wiki

- [x] rename hotword to keyword
- [x] save
- [x] saveandquit
- [x] quit

**Comment by BenBals** [comment]
Please use the term "keyword".

**Comment by phlprcks** [comment]
wiki has been updated

**Comment by BenBals** [comment]
Good job! :100: This was irking me for so long.
