### ISSUE TITLE
add more system functions

### ISSUE THREAD

**Issue by phlprcks** [hpi-swa-teaching/Algernon-Launcher#123]
As a user I want to use Algernon for more "routine" system functions calls in order to be more productive and harmonize my workflows.

So far with #50 you can *save*, *quit* and *saveandquit* the image using Algernon. Possibly adding more functions such as *save as...*, *save as new version*, *recover changes* (after image has crashed) and maybe even *update squeak* or the like is useful for the user.

**Comment by TheGrayStone** [comment]
This behavior is implemented by the issue #175, so this can be closed.
