### ISSUE TITLE
Fix the =-Space Expression Bug

### ISSUE THREAD

**Issue by sinnaj-r** [hpi-swa-teaching/Algernon-Launcher#130]
At the Moment the ALGExpressionType>>getCommand Method will cut the first two characters from the input and run the rest. That means that only "= [EXPRESSION]" will work not "=[EXPRESSION]".
This should be an quite easy fix we should do before submission.

Remember:
- [x] Write a regression test

**Comment by BenBals** [comment]
Hint: Factor out the commonalities of this test and make it callable with a different string:

```smalltalk
testExpressionDoIt
	| expressionItem oldSystemWindows |
	self runQuery: '= SystemBrowser default open'.
	expressionItem := self items detect: [:each| each algerType typeName = 'Expression'].
	self assert: expressionItem notNil.
	oldSystemWindows := self currentSystemWindows.
	self doActionForItem: expressionItem withName: 'do'.
	self assert: (self findNewSystemWindowsByLabel: 'System Browser' old:  oldSystemWindows) notEmpty.
```

**Comment by kej-jay** [comment]
do oder = weg

**Comment by BenBals** [comment]
Pseduocode:
```
if string first == '='
then return string[1:]
else return string[2:]
```

**Comment by kej-jay** [comment]
> 
> 
> Hint: Factor out the commonalities of this test and make it callable with a different string:
> 
> ```smalltalk
> testExpressionDoIt
> 	| expressionItem oldSystemWindows |
> 	self runQuery: '= SystemBrowser default open'.
> 	expressionItem := self items detect: [:each| each algerType typeName = 'Expression'].
> 	self assert: expressionItem notNil.
> 	oldSystemWindows := self currentSystemWindows.
> 	self doActionForItem: expressionItem withName: 'do'.
> 	self assert: (self findNewSystemWindowsByLabel: 'System Browser' old:  oldSystemWindows) notEmpty.
> ```

It would be greatly appreciated, if you could explain to me again, what you want me to do with this test. I will bring it up in our meeting tomorrow

**Comment by kej-jay** [comment]
Helper umbauen zum Var reinpassen, 3/4 Tests schreiben, mit =,=_, do,do_
