### ISSUE TITLE
Update Class Diagram and High Level Documentation

### ISSUE THREAD

**Issue by BenBals** [hpi-swa-teaching/Algernon-Launcher#132]
- [x] Redo Class Diagram
- [x] Write about architecture in class comments
- [x] Places to start in the ALGCore class comment
- [x] Write intro to the project

**Comment by BenBals** [comment]
I have written a bit on the Architecture page in the Wiki.

Do you think this is enough, @kej-jay?

**Comment by kej-jay** [comment]
I like your text. Class diagram is up now too!
This should be done then? @BenBals

**Comment by BenBals** [comment]
Yes. Thank you.
