### ISSUE TITLE
Include Video Somewhere on GitHub

### ISSUE THREAD

**Issue by BenBals** [hpi-swa-teaching/Algernon-Launcher#133]

**Comment by sinnaj-r** [comment]
@kej-jay I just saw that there's an (very) old screencast linked in the wiki, what about using our new Screencast (made for the Lightning-Talks). I think I sent you the Cast as something like `Algernon_Demo`.

**Comment by kej-jay** [comment]
> 
> 
> @kej-jay I just saw that there's an (very) old screencast linked in the wiki, what about using our new Screencast (made for the Lightning-Talks). I think I sent you the Cast as something like `Algernon_Demo`.

Is in the works. Link is edited already and vimeo is still rendering. In a couple of minutes it should be fine
