### ISSUE TITLE
Increase Code Coverage

### ISSUE THREAD

**Issue by BenBals** [hpi-swa-teaching/Algernon-Launcher#140]
At the Moment we have around 97% Code Coverage, obviously that isn't bad, but we should be able to reach 99% or 100% Coverage. There are just some new methods which have no tests yet.

The Uncovered Methods (at the time of writing):

![Screen Shot 2020-08-01 at 12 35 29 PM](https://user-images.githubusercontent.com/2962736/89099997-ce4eb600-d3f3-11ea-8fe6-5e3ef3137d66.png)

_Both the Coverage and Screenshot are from the soon-to-be-merged `fix-lints-janni-ben` branch_

**Comment by BenBals** [comment]
@sinnaj-r are you currently able to run the tests with coverage?

**Comment by sinnaj-r** [comment]
Not on my MacBook, but under Windows it's (often) working.

**Comment by BenBals** [comment]
Would you then be able to take a look at the coverage report?

**Comment by BenBals** [comment]
We can use https://coveralls.io/builds/32504656 to look at the coverage now.

**Comment by sinnaj-r** [comment]
> Would you then be able to take a look at the coverage report?

Yes, I'll look into that.

> We can use https://coveralls.io/builds/32504656 to look at the coverage now.

It's great that this is finally working. Is there a possibility that we can display coverage changes automatically in PRs?
Further, should we adjust the readme of the dev branch, so that it shows its own coverage and not the coverage of the master ?

**Comment by BenBals** [comment]
> It's great that this is finally working. Is there a possibility that we can display coverage changes automatically in PRs?

I don't know if you can see the changes, but the current coverage is displayed in the checks area for all prs whose branches include the coverage code.

>  Further, should we adjust the readme of the dev branch, so that it shows its own coverage and not the coverage of the master ?

That would be nice, but would be overwrite master if we make a submission pr.

**Comment by sinnaj-r** [comment]
> > It's great that this is finally working. Is there a possibility that we can display coverage changes automatically in PRs?
> 
> I don't know if you can see the changes, but the current coverage is displayed in the checks area for all prs whose branches include the coverage code.

Ah, I see; Thats great 👍 

> > Further, should we adjust the readme of the dev branch, so that it shows its own coverage and not the coverage of the master ?
> 
> That would be nice, but would be overwrite master if we make a submission pr.

How about displaying two Coverage Counts, one for master and one for dev ?

**Comment by BenBals** [comment]
Sounds good, what do you think @phlprcks?

**Comment by phlprcks** [comment]
makes sense to me, see PR #159 @sinnaj-r

**Comment by sinnaj-r** [comment]
> makes sense to me, see PR #159 @sinnaj-r

Thank you 👍
