### ISSUE TITLE
Cleanup Git(-hub)

### ISSUE THREAD

**Issue by sinnaj-r** [hpi-swa-teaching/Algernon-Launcher#142]
Make the Git (-hub) ready for the next team.
This includes: 
- [x] Remove Merged/stale/dangling Branches
- [x] Archive/Complete Milestones
- [x] Look through open issues add/remove description/labels/etc if needed

**Comment by BenBals** [comment]
Do you feel comfortable with a task like this @robertkirsten?

**Comment by phlprcks** [comment]
I would take over so that @robertkirsten can complete his #134 which seems more urgent to me.

**Comment by robertkirsten** [comment]
Closed milestones.
