### ISSUE TITLE
Installation in Squeak 5.3 emits deprecation warning

### ISSUE THREAD

**Issue by sinnaj-r** [hpi-swa-teaching/Algernon-Launcher#143]
When Upgrading to a new Algernon Version in Squeak with the provided Snippet (as created in #125 ), you have to dismiss ~20 Deprecation Warnings.

**Comment by BenBals** [comment]
We should definitely never use deprecated code.

Can you post the warnings as I cannot reproduce that? Then I can take a look.

**Comment by sinnaj-r** [comment]
A quick debug shows, that we install SWALint as a dependency and that this module has the deprecations (or triggers them in Squot). You can see the same Warnings in the CI-Logs. 
I'm not sure why we install SWALint, but if we can't remove it, we will have to wait for them to fix the issue. (Might be this one https://github.com/hpi-swa-teaching/SwaLint/issues/43 or this one at Squot: https://github.com/hpi-swa/Squot/issues/266)

**Steps to reproduce:**
Download a fresh Squeak 5.3 Version. Run the Install Snippet for the `development` branch.


**I get the following warnings:**

![Screen Shot 2020-08-01 at 1 18 15 PM](https://user-images.githubusercontent.com/2962736/89100744-da3d7680-d3f9-11ea-87b3-21b919795428.png)

**Comment by BenBals** [comment]
Thank you.

The thing is that we need SWA Lint as a dependency to run the lints in CI. I don't know if there is a way to not install that for a normal installation.

Consider contacting @MrModder via email about this. I feel like he will be able to offer advice.

**Comment by LeonMatthes** [comment]
The culprit is this code in the baseline:
```smalltalk
 spec
        group: 'default' with: #('Algernon');
        group: 'Tests' with: #('AlgernonTests');
	group: 'default' with: #('PlugIns');
	group: 'portability' with: #('PlugIns');
	group: 'Core' with: #('SwaLint-Core');
	group: 'PlugIns' with: #('SwaLint-PlugIns').
```
Specifically, `group: 'default' with: #('PlugIns');` requires the SwaLint-Plugins for the default installation of Algernon.
If you were to remove this line and change the 'Tests' package to require the Plugins, SwaLint would only be loaded whenever the tests are loaded.

i.e.:
``` smalltalk
 spec
        group: 'default' with: #('Algernon');
        group: 'Tests' with: #('AlgernonTests' 'PlugIns');
	group: 'portability' with: #('PlugIns');
	group: 'Core' with: #('SwaLint-Core');
	group: 'PlugIns' with: #('SwaLint-PlugIns').
```

Before taking such a step you should be very confident that the default installation of Algernon does not require them.
