### ISSUE TITLE
Add Coveralls Badge to README

### ISSUE THREAD

**Issue by BenBals** [hpi-swa-teaching/Algernon-Launcher#149]

**Comment by BenBals** [comment]
Could you do this @phlprcks?

**Comment by phlprcks** [comment]
@BenBals I set the badge to show the coverage of the master branch. Do you think we should also inlcude a badge for development somewhere in the readme?

**Comment by BenBals** [comment]
I think it's fine the way it is. Our code will (hopefully) be merged into master soon anyway.
