### ISSUE TITLE
doIt does not work

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swa-teaching/Algernon-Launcher#16]
As a user I want to call the `do` hotword to run smalltalk code.
 
# Acceptance criteria
- [x] The do hotword runs the given code.
- [x] In comparison to `=`, it does not print the result.

**Comment by LeonMatthes** [comment]
Estimated effort: 3

**Comment by BenBalsInsecure** [comment]
Spent 2 People and 1.5h.
