### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-teaching/Algernon-Launcher#165]
I just stumbled upon this project, found it great, and felt like noting down some ideas for further improvements & extensions:

- Improve keyboard hints for hierarchical navigation: The symbol indicates an arrow, but one should use tabs. Exchange the icon.
- Improve mouse support in the launcher (e.g., yellow button clicks seem to ignore the existence of the launcher completely). Support scrolling in the list instead of truncating it might also be a nice enhancement.
- Automatically turn on Algernon when loaded via the Metacello script (this is possible using a `postLoadDoIt`)
- Bug: When navigating in the search text field using the arrow keys, the list selection jumps back to the first hit in the list.
- "Evaluate text field" currently only prints the result into a Transcript (e.g., "3 -> 3" for "1 + 2"). For other expressions such as `Object new`, I receive an MNU error.
- Proposal: Show live (printIt) results of expression while typing. This could be achieved easily without harming the image by using [Sandbox](https://github.com/LinqLover/SimulationStudio/).
- Search for open windows and bring to front/maximize/close them when selected (by providing another submenu with relevant actions).
- Integrate more menu commands such as the doIt list, extras, or project management into the launcher.
- Add a short command for installing Squeak updates (as known via the first menu in the main docking bar).

**Comment by TheGrayStone** [comment]
This issue has been split up into a few different ones as follows:

- #166 : Improve hierarchical navigation
- #168 : Improve yellow mouse button support
- #170 : Automatically turn on Algernon when loaded via the Metacello script
- #171 : Bug: List selection jumps to first item when using arrow keys
- #173 : Print live results
- #174 : Support actions for open windows
- #175 : Support more (squeak) menu commands

Please use these issues if you have anything more to add or to monitor their development status. If you feel like a request of yours is not covered by any of these issues, feel free to raise it as a seperate one.

**Comment by LinqLover** [comment]
Thank you very much, @TheGrayStone! I am looking forward to seeing this wonderful project growing! 🚀
