### ISSUE TITLE
Improve yellow mouse button support

### ISSUE THREAD

**Issue by FranzSw** [hpi-swa-teaching/Algernon-Launcher#168]
As a user I want to be able to yellow-click on the result list in order to inspect it

## Acceptance Criteria
- [ ] Result list & items is yellow-clickable (inspectable)

**Comment by BraunTom** [comment]
Ich sehe keinen Use case für das yellow button menu (was sollte dort denn angezeigt werden?). Es sollte nur sichergestellt werden, dass sich kein yellow button menu öffnet.
