### ISSUE TITLE
Bug: Evaluate Text Field ignores first two characters

### ISSUE THREAD

**Issue by FranzSw** [hpi-swa-teaching/Algernon-Launcher#172]
## Reproduction
1. Open Algernon
2. Type in `Object new` (or `2+2`)
3. Select Evaluate text field

(if you prepend two whitespaces, results are correct)

## Issue
First two characters are ignored, which results in wrong results or errors 

e.g. Object new -> Error: `ject is Undeclared`
1+2 -> 2

**Comment by Olliwehr** [comment]
It seems this issue is closely related to #130 and #157, isn't it?

Edit: Yip, after quick research, i think the following code-snippet in `ALGExpressionType >> getCommand` should do the job 😅 

```
	startIndex := 1.
	textFieldContents first = $=
		ifTrue: [startIndex := 2].
	(textFieldContents startsWith: 'do')
		ifTrue: [startIndex := 3].
```

instead of

```
        textFieldContents first = $=
		ifTrue: [startIndex := 2]
		ifFalse: [startIndex := 3].
```
