### ISSUE TITLE
Change default activation string

### ISSUE THREAD

**Issue by niklasmohrin** [hpi-swa-teaching/Algernon-Launcher#178]
The default activation string should be `<Ctrl-space>` instead of `<Cmd-space>`, because the latter conflicts with the SpotLight hotkey and having `Cmd` is weird on some platforms, according to customer.

# Acceptance criteria

- [x] activation string changed
- [x] possible conflicts with other hotkeys investigated

# Tip by tutor
`Smalltalk platformName`

**Comment by bewee** [comment]
I think that `<Ctrl-space>` is a bad idea, since that's already the shortcut for auto completion suggestions

**Comment by niklasmohrin** [comment]
Soooo, we decided that we don't want `Alt` or `Cmd`, we don't want `Ctrl+Shift` so only `Ctrl+<some letter>` remains. The only letter on the left half of my quertz keyboard that I don't already associate with another action is `Ctrl-r` (seems to do nothing right now :bangbang: ). On the right hand, there are some options, maybe ~~`Ctrl-o`~~(opens a new workspace, some other meaning in world context), `Ctrl-u` (sets alignment), `Ctrl-h` (does _something_ in world, nothing happens though), `Ctrl-j` (seems to reload workspace window), `Ctrl-k` (opens some prompt about font or so), ~~`Ctrl-l`~~ (discards changes in workspace).

I guess `Ctrl-r` is fine, can any of you verify that `ctrl-r` is not important?

**Comment by LinqLover** [comment]
<kbd>Alt</kbd> + <kbd>r</kbd>/<kbd>Ctrl</kbd> + <kbd>r</kbd> on Windows is used to restore the display which removes all drawing invalidations. You can see it in effect by doing the following:

```smalltalk
'foo' displayAt: 0 @ 100.
"Now press alt + r"
```

I can speak for the SWA group and say that some people including myself actually use this shortcut quite frequently. :-)

Just another idea, did you consider a keyboard sequence such as <kbd>Ctrl</kbd>, <kbd>Ctrl</kbd> (i.e. press the key twice in a certain interval)? For such a meta action like invoking Algernon I think this might actually be a more catchy shortcut than a random letter. Just my 2 cents, though. :-)
