### ISSUE TITLE
improve explore instances action

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swa-teaching/Algernon-Launcher#18]
As a user when I explore instances I want one window with all instances not one window per instance in order to make the result not clutter up the screen.

This issue is based on a request by Marcel Taeumel. The original text is reproduced here: 
> Könntet ihr bei der Aktion "Explore Instances"  einen einzigen ObjectExplorer öffnen?  Morph allInstances explore. Morph allSubInstances explore.  Das würde die Auswirkungen der Aktion vorhersehbar machen. Die Aktion "Inspect Instances" könnte entfallen.  
> Viele Grüße, Marcel

# Acceptance Criteria
- [x] make algernon always open one window with all instances instead of one window per instance

**Comment by TheGrayStone** [comment]
Also, when exploring e.g. a workspace, multiple instances are shown to exist, although only one is present as a window. The reason behind that should probably be checked out as well.
