### ISSUE TITLE
directly search for methods

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swa-teaching/Algernon-Launcher#19]
As a developer I want to find methods without specifying the class first in order to reduce the time it takes to find something in Algernon.

# Acceptance Criteria
- [x] algernon finds methods without needing a specified class

# Old Description
Allow for a direct search for methods on top level navigation.
Currently search for methods is only possible within classes (class view when right arrow key was hit).

**Comment by sinnaj-r** [comment]
The code for this is already existing and fully functional. See MethodType algertemList and a lot of method related functions on the ALGItem; the main problem seems to be that speed because of the ~80.000 added items to search through.

**Comment by BenBals** [comment]
Maybe it ties into #1 then?
