### ISSUE TITLE
keep breadcrumbs as a part of the last input

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swa-teaching/Algernon-Launcher#20]
The last input in Algernon is currently saved. 
But when navigating with a right arrow key hit in a class and typing new words only this last input is kept. So when reopening Algernon ~this last input is displayed, but on top level and not in the correct navigation hierarchy~ Algernon jumps back to the first layer results, discarding the last hierarchical navigation.

# Acceptance Criteria
- [ ] When closing Algernon while in a layer > 1 and then reopening it, restore the last hierachical navigation
- [ ] Also restore last query string in this layer
- [ ] Make this behavior optional via an entry in the preferences

**Comment by niklasmohrin** [comment]
We concluded that we don't really like _this exact behavior_. I think that it would be annoying if you always had to leave previously entered dialogs :man_shrugging: 

I could imagine that we remember the search string in the nested search box and maybe even where the keyboard focus in the result list was before exiting the launcher.
