### ISSUE TITLE
Implement unfinished ALGTypes

### ISSUE THREAD

**Issue by louiskirsch** [hpi-swa-teaching/Algernon-Launcher#21]
- ALGRepositoryType (make sure it does the right thing and register in ALGItemProvider)
- ALGMorphType and subclasses (make sure it does the right thing and returns items in algertemList)

# Acceptance Criteria
- [ ] unclear

**Comment by annkatrinkuessner** [comment]
"save" ALGAction works with ALGRepositoryType. Therefore currently not working. Should also be fixed, when targeting this issue.
