### ISSUE TITLE
Open tools from results, not only their class

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swa-teaching/Algernon-Launcher#23]
As a user when I search for the name of a tool I want to be able to open that tool and not only its claas definition in order to use Algernon as a general purpose launcher.

# Acceptance Criteria
- [x] the `open` hotword can directly open a tool (rather than its class) additionally to it's existing functionality of opening Apps
  - A tool is any program listed in the Tools dropdown

# Old description
Algernon should also allow developers to open tools directly from the launcher (Browser, Workspace, Transcript, ...)

**Comment by LeonMatthes** [comment]
Estimated effort: 5

**Comment by LeonMatthes** [comment]
Currently not working in my image, needs further testing

**Comment by BenBals** [comment]
Does not work in my image either.

**Comment by BenBals** [comment]
I have written a test and (hopefully) a fix in #47.
