### ISSUE TITLE
hitting the right arrow key, when no result is displayed, throws an error

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swa-teaching/Algernon-Launcher#3]
![upload_6_1_2016_at_7_47_44_pm](https://cloud.githubusercontent.com/assets/10118059/15723623/9596a512-2843-11e6-862e-32ccc89ee876.png)

**Comment by louiskirsch** [comment]
Fixed in a45f6dfba2da8009490ac06abc91874aa2b3b1ff
