### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by BenBalsInsecure** [hpi-swa-teaching/Algernon-Launcher#32]
As a contributor I want to see whether may changes make the tests fail in order to keep up the code quality.

To be compliant with the software development process outlined in the introductory lecture, we will use GitHub Actions for CI/CD.

This needs to be set up.

**Comment by BenBalsInsecure** [comment]
Should we remove travis?

I think so.

**Comment by BenBalsInsecure** [comment]
Do you want to run the tests on windows and mac as well?

**Comment by BenBalsInsecure** [comment]
What remains is setting up coverage reporting. I have been in touch with the developers of smalltalkCI as the the documentation is not up to date.

**Comment by BenBalsInsecure** [comment]
Spent 2h.

**Comment by sinnaj-r** [comment]
Is it possible that the Windows Actions always run successfully, regardless of the test results?

**Comment by BenBals** [comment]
Yes, but I don't know why.

**Comment by BenBals** [comment]
@sinnaj-r this was fixed by #66.

**Comment by sinnaj-r** [comment]
@BenBals  Can we close this Issue ?

**Comment by BenBals** [comment]
Yes.
