### ISSUE TITLE
Help inside Algernon

### ISSUE THREAD

**Issue by BenBalsInsecure** [hpi-swa-teaching/Algernon-Launcher#33]
As a user new to Algernon I want to have keyword that displays all commands available to me I order to interactively discover Algernon.

# Acceptance Criteria
| Client | Team | Text |
|--------|------|------|
| :heavy_check_mark:  | :heavy_check_mark: | entering `help` gives a list of hotwords |
|  :heavy_check_mark: | :heavy_check_mark: | entering `help [keyword]`will display an explanation of a keyword |
| :heavy_check_mark: | :heavy_check_mark: | the keyword is documented in the Wiki |

**Comment by BenBalsInsecure** [comment]
It might be a good idea to transfer the keyword `?` to also display the help.

**Comment by BenBals** [comment]
Todos
- [x] Find out what `printout` does
- [x] Write Help texts
- [x] Write filters
- [x] ensure help is top result for keyword without operant
- [x] prevent or circumvent overflow (removed)
- [x] implement action that opens the keyword

**Comment by BenBals** [comment]
We have investigated the overflow issue a bit and would bounce it back to the team that tried to fix it since a fix only pertaining to help texts would be hacky and bad for the architecture and fixing it for all resultitems would be out of scope and infringe on the autonomy of that team.

**Comment by BenBals** [comment]
I have written the remaining help texts. In light of issue #57, I have only documented one way of searching for class comments in order to not clutter up the help menu.

**Comment by BenBals** [comment]
I have also implemented the action. I think the pr should be ready for review.

@sinnaj-r would you please take a look and add tests or refactor if need be? Feel free to un-draft the pr and request reviews once you are done.

**Comment by BenBals** [comment]
It seems like `SortedCollection>>take:` is only available on Squeak 5.3 and not on the earlier versions. What is our strategy for dealing with that?

**Comment by BenBals** [comment]
I think the build targets are for the client to decide.

@MrModder, what versions of Squeak should we support?

**Comment by LeonMatthes** [comment]
Regarding version support: At least one version before 5.3 would be good.
But if it is very hard to replace the take function with something else I might be pursuaded otherwise.

**Comment by BenBals** [comment]
We have replaced it, it's not that hard. It was just a general question that came up due to this small issue. We continue to support 5.1, 5.2, 5.3 and trunk. (I'm acutally using trunk, so we have manual testing there in addition to the provided swt-squeak).

**Comment by BenBals** [comment]
@MrModder, is there a reason you reopened the issue?

**Comment by LeonMatthes** [comment]
Closing the issue was a mis-click on my part, so I reopened it. The issue shouldn't be closed until it has been accepted in the customer meeting.
