### ISSUE TITLE
Hide top results from full list

### ISSUE THREAD

**Issue by BenBalsInsecure** [hpi-swa-teaching/Algernon-Launcher#34]
As a user I want top results to be hidden from the full result list because I'm confused by seeing the same result twice and want to better utilize the screen real estate.

# Acceptance Criteria
| Team | Client | Description |
|-|-|-|
| :heavy_check_mark:  | :heavy_check_mark:  | any result that is displayed in the top results is not displayed again in the full list |

**Comment by LeonMatthes** [comment]
Estimated effort: 5
