### ISSUE TITLE
Algernon doesn't grey out the screen correctly when hovering a listview

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/Algernon-Launcher#36]
## Steps to reproduce
Hover over a listview (e.g. in a open Browser) and open Algernon via it's assigned shortcut.
Do not type anything into Algernon yet.

## Unexpected behavior
The listview receives a grey overlay, but the rest of the window is not greyed out.

## Expected behavior
The entire window is greyed out immediately

Note: When characters are entered into Algernon, the entire image is greyed out successfully.

**Comment by BenBals** [comment]
I can reproduce this behavior.

**Comment by MrModder** [comment]
Estimated effort: 3

**Comment by BenBals** [comment]
Seems to have been fixed accidentally while implementing the movement of Algernon.
