### ISSUE TITLE
Check existing Test Cases

### ISSUE THREAD

**Issue by sinnaj-r** [hpi-swa-teaching/Algernon-Launcher#38]
As a contributor I want the existing tests to succeed.

**Comment by BenBalsInsecure** [comment]
The Test `ALGAction>>testRepositoryTypeAlgertemListWith` fails. It seems to me like the code is correct, but there is no repo to find in the environment. We need to figure out how to do test setup and teardown programmatically.

**Comment by sinnaj-r** [comment]
I found the Issue: The Test checks the Monticello-Repository-Search; therefore it searches for it's own Repo in Monticello, but it won't find it there, because its installed via Squot. If you test for a different package installed via Monticello (e.g. 'JSON') the test will succeed.

**Comment by sinnaj-r** [comment]
Maybe we could test for the package 'Monticello' - it should be there by default

**Comment by BenBalsInsecure** [comment]
Yep, that's also what I thought. I'll prepare a PR.

**Comment by BenBalsInsecure** [comment]
Spent 0.5h.
