### ISSUE TITLE
Code Coverage too low

### ISSUE THREAD

**Issue by BenBalsInsecure** [hpi-swa-teaching/Algernon-Launcher#45]
I'm currently trying to figure out how to include coverage results in our CI pipeline. While doing that I noticed that the coverage hovers around 83%. Which is not nearly acceptable. I would aim for at least 95%. That's around the percentage where we can really start relying on our tests.

You can have a look yourself at https://coveralls.io/github/hpi-swa-teaching/Algernon-Launcher?branch=development.

Any thoughts? How would you prioritize this?

**Comment by BenBalsInsecure** [comment]
I'm experiencing issues with the local test coverage in Test Runner getting stuck in an infinite loop.

**Comment by BenBalsInsecure** [comment]
The fix for this issue is to replace `valueUnpreemptively` with `value` in the method `TestRunner >> #collectCoverageFor:`.

**Comment by sinnaj-r** [comment]
@BenBals should we close this Issue, as the Coverage-Integration is merged now and this Issue is "replaced" by Issue #140 ?
