### ISSUE TITLE
overlapping search field and result list

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swa-teaching/Algernon-Launcher#5]
occurs when having too many results in search

<img width="500" alt="screen_shot_2016-05-09_at_8 10 54_pm" src="https://cloud.githubusercontent.com/assets/10118059/15723769/47925b1c-2844-11e6-8cef-198f0cb6f368.png">
<img width="520" alt="screen_shot_2016-05-09_at_8 12 28_pm" src="https://cloud.githubusercontent.com/assets/10118059/15723768/479151a4-2844-11e6-8fee-b7ac793f55ff.png">

**Comment by jonaschn** [comment]
fixed
