### ISSUE TITLE
 Actually implement a Fuzzy-Matching Algorithm

### ISSUE THREAD

**Issue by sinnaj-r** [hpi-swa-teaching/Algernon-Launcher#56]
Algernon currently does not do fuzzy matching. It does regular substring matching and uses levenshtein distance to sort only after the filtering.

Try to enter `ALGKore`, it should return the `ALGCore` class, but it doesn't.

This might require significant reengineering of internal infrastructure.

# Acceptance Criteria
| Client | Team | Description |
|--|--|--|
| :heavy_check_mark: | :x: | Typing the initials of a query makes the result show up |
| :heavy_check_mark: | :x: | Fuzzy matching works with hotword queries |
| :heavy_check_mark: | :x: | Search does not feel slow |

# Old Version
As a user I want search results that are _closer_ to my search term. 
E.g. when typing "ALG" I want result for the classes "ALG..." and not "ABC".

So we have to replace the Levenshtein distance with a more suitable algorithm.

**Comment by BenBals** [comment]
See https://en.wikipedia.org/wiki/Approximate_string_matching for a basic introduction.

**Comment by BenBals** [comment]
For better metrics than Levenshtein distance see https://en.wikipedia.org/wiki/String_metric.

**Comment by BenBals** [comment]
See https://arxiv.org/pdf/2004.08350.pdf for a comprehensive survey.

**Comment by BenBals** [comment]
One Algorithm I just came up with (that's definitely not original to me) is to do the following:
1. All characters of the search must be in the result in the right order.
2. We score the result by the number of characters between the first and the last of the query.

E. g. `Algro` would match `Algernon` and have a (negative) score of 3 as the letters `e` and `n` (twice) are missing..

This behavior is similar to what a lot of fuzzy matchers do. It's not quite as powerful, but has certain advantages.

- Can be computed in O(n) and with far lower constants.
- Gives better result for short queries or long search strings.

**Comment by BenBals** [comment]
@MrModder we just found out that Algernon does not do fuzzy matching. What do you think?

**Comment by BenBals** [comment]
@kej-jay We should add acceptance criteria. Do you have any ideas? Mine feel inprecise.
