### ISSUE TITLE
Intermittend failure of testCategoriesVisible and testBreadcrumbs

### ISSUE THREAD

**Issue by BenBals** [hpi-swa-teaching/Algernon-Launcher#59]
See https://github.com/hpi-swa-teaching/Algernon-Launcher/pull/46/checks?check_run_id=697036504 for an example.

Another example: https://github.com/hpi-swa-teaching/Algernon-Launcher/pull/47/checks?check_run_id=704080796.

**Comment by BenBals** [comment]
It seems like this issue only arises on macos. I would be cool if @sinnaj-r and @robertkirsten could investigate.

**Comment by robertkirsten** [comment]
Tests are running by now.
