### ISSUE TITLE
tooltip for class comments 

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swa-teaching/Algernon-Launcher#6]
As a user I want to see the complente class comment I found right in Algernon in order to avoid switching to another program. 

# Original Description
so that the user can identify class comments in search results easier . Idea was to show a tooltip on the right side of the result list

# Acceptance Criteria
- [ ] A class comment in the search results can be expanded to be fully read in Algernon.

**Comment by LeonMatthes** [comment]
For inspiration you might want to look into the [Autocompletion's](https://github.com/mrmodder/autocompletion) ECDetailMorph.
It provides a detail view for results using `Ctrl+right`.
