### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by BenBals** [hpi-swa-teaching/Algernon-Launcher#61]
- [x] Update Authors
- [x] Upadate CI and Coverage Badges
- [x] Add GitHub description

**Comment by phlprcks** [comment]
#70

**Comment by BenBals** [comment]
Please fix the badges at the top of the readme.

**Comment by phlprcks** [comment]
@BenBals you mentioned to have a _About_ section. I don't see the benefit for that bc both in the readme as well as the wiki there are short descriptions provided already. What is you opinion on that?

**Comment by BenBals** [comment]
I meant the GitHub-inbuilt description. That is displayed in many places where the repo is listed, it may get users to click on the repo, so we should have it.

Could you please also update the screenshot?

**Comment by phlprcks** [comment]
@MrModder do you have the permission to edit the github "about" section for the repo? I can't.
If so I suggest to add following as a description:
"Algernon is a productivity tool for Squeak programmers; your personal assistant for Squeak. Algernon aims to make programming in Squeak faster and more keyboard centric. It provides lightning quick access to the core functionalities (classes, methods, morphs, tests, repositories ...) and even gives you a quick way to evaluate Smalltalk expressions."

**Comment by sinnaj-r** [comment]
@phlprcks Please also add a paragraph/disclaimer to the readme that the first start of Algernon might be slow - but that all subsequent runs are much faster. 🙂

**Comment by BenBals** [comment]
@phlprcks Consider sending an email to our tutor.

**Comment by LeonMatthes** [comment]
> @MrModder do you have the permission to edit the github "about" section for the repo? I can't.
> If so I suggest to add following as a description:
> "Algernon is a productivity tool for Squeak programmers; your personal assistant for Squeak. Algernon aims to make programming in Squeak faster and more keyboard centric. It provides lightning quick access to the core functionalities (classes, methods, morphs, tests, repositories ...) and even gives you a quick way to evaluate Smalltalk expressions."

Great to hear you're engaged in the presentation of your project. I've updated the about section as requested.

**Comment by BenBals** [comment]
Thank you very much, @MrModder!

We really believe that every Squeak developer should use Algernon.

**Comment by phlprcks** [comment]
> 
> 
> @phlprcks Please also add a paragraph/disclaimer to the readme that the first start of Algernon might be slow - but that all subsequent runs are much faster. 🙂

@sinnaj-r is included in the PR of branch 61 (#152 ). Please feel free to close this issue if you're ok with the disclaimer :)
