### ISSUE TITLE
Automatically find and delete new PluggableSystemWindows

### ISSUE THREAD

**Issue by BenBals** [hpi-swa-teaching/Algernon-Launcher#63]

**Comment by BenBals** [comment]
@sinnaj-r Is this the behavior we have implemented currently?

(Note that this refers to testing.)

**Comment by sinnaj-r** [comment]
> @sinnaj-r Is this the behavior we have implemented currently?
> 
> (Note that this refers to testing.)

Yes, it is. In my opinion this issue can be closed.
