### ISSUE TITLE
Better keybindings

### ISSUE THREAD

**Issue by BenBals** [hpi-swa-teaching/Algernon-Launcher#73]
As a user I want to be able to edit the text I entered into Algernon using my arrow keys.

Currently it is not possible to use the arrow keys in algernon as those are reserved for navigating the children.

We should consider changing that behavior.

This issue was raised in working on #17, see the discussion at #72.

**Comment by LeonMatthes** [comment]
Suggested new keybindings:
- `Tab` to "go into" the item.
- `Shift+Tab` to "go back" when already in an item.
- Arrow keys for cursor navigation.
This would mimic the behavior of the Autocompletion.

Does anyone have insight on how tools like Spotlight/Alfred implement this behavior?

Also, the arrow icon that is currently used to indicate "go into" (🡒) could be replaced by a "tab symbol" (↹ or ⇥, possibly depending on client platform)

**Comment by BenBals** [comment]
Albert on Linux uses Tab for similar behavior.

**Comment by sinnaj-r** [comment]
Spotlight does not know the concept of children or actions, so Tab does not do anything.

Alfred uses Tab to complete the current search term for the selected item. (Search for "test", "TestApp.app" is displayed as the result; Tab sets the search term to "TestApp.app"). 
Shift-Tab Selects the entire current search term.

The arrow keys are used in Alfred for cursor navigation, but also - when the cursor is rightmost - to display the Children. And in the Children view to trigger an action. Esc is used to navigate out of the children again.

In both apps an Enter triggers the default action.
Another interesting feature is that Alfred allows to change the default action by pressing Shift, Option or Command.

--

Personally, I think that navigating in and out with Tab is a good solution here, too. I also think that Tab should also be able to trigger actions (in addition to Enter). 
I furthermore feel it would be nice to give the user additionally the possibility to navigate with the arrow keys only, comparable to Alfred with the right and left arrow key to move the cursor, navigate in/out and to trigger actions.

Algernon is mainly meant to be a fast productivity tool and therefore several options for the user to navigate the app with the keys he is most comfortable with, are quite important.

**Comment by BenBals** [comment]
Take look at `ALGCore class>>initializeGlobalKeyBindings`

```smalltalk
initializeGlobalKeyBindings
	KeyBindings := Dictionary newFrom:
		{ '<down>' -> [:anEvent :morph | morph selectNext]. 
		'<up>' -> [:anEvent :morph | morph selectPrevious]. 
		'<right>' -> [:anEvent :morph |  morph showChildList]. 
		'<left>' -> [:anEvent :morph | morph showParentList]. 
		'<escape>' -> [:anEvent :morph | morph deactivate: anEvent hand]. 
		'<cr>' -> [:anEvent :morph | morph doActionOnSelectedEvent:anEvent] }
```
