### ISSUE TITLE
Dynamic adjustment of font sizes

### ISSUE THREAD

**Issue by sinnaj-r** [hpi-swa-teaching/Algernon-Launcher#74]
As a user I want readable texts regardless of Monitor size or dpi.

This was also discussed in PR #68.
You might want to look at the Size functions of the TextStyle class, e.g. `TextStyle default fontOfPointSize`

**Comment by LeonMatthes** [comment]
The result list already seems to use the default text size, which can be increased/decreased under `Extras>Themes&Colors`.

So does this US only affect the input textfield?
