### ISSUE TITLE
"Tidying up" the tests

### ISSUE THREAD

**Issue by sinnaj-r** [hpi-swa-teaching/Algernon-Launcher#88]
Although the tests in #81 have already been cleaned up to the point where the subclass relationship should be correct, the tests are often not grouped into meaningful classes. Also the categories of the individual methods are not consistent. So we urgently need to tidy things up there so that tests are easier to find and certain test sets can be run more precisely.

**Comment by phlprcks** [comment]
Most changes have accidently been pushed directly to the development branch (weird default setting in squeak git browser). So we decided to leave it there and comment on the commits for the review.
So please also check the commits to the development branch on Aug 1st. (e.g. https://github.com/hpi-swa-teaching/Algernon-Launcher/commit/c933896f012a5bf564c79fbddf9448b6231eaa50 )

**Comment by BenBals** [comment]
See my comment on this commit: https://github.com/hpi-swa-teaching/Algernon-Launcher/commit/c933896f012a5bf564c79fbddf9448b6231eaa50

Also, I mentioned @sinnaj-r in that one, but I'm not sure it worked.

**Comment by BenBals** [comment]
I'm not sure if these changes are what @sinnaj-r meant by "tidying up the tests". I think he was more refering to these things
- factor out duplication
- remove conditional test logic
- write fixtures
- write helpers
- write custom asserts
- use child tests
- etc.

But I will defer to him on that.

**Comment by sinnaj-r** [comment]
> I'm not sure if these changes are what @sinnaj-r meant by "tidying up the tests". I think he was more refering to these things
> 
> * factor out duplication
> * remove conditional test logic
> * write fixtures
> * write helpers
> * write custom asserts
> * use child tests
> * etc.
> 
> But I will defer to him on that.

In fact, I was originally concerned with the correct classification of the tests(-methods) into classes and categories.

However, the points you raised are still important - I would have associated them with Issue #134, but I can also understand if that would be too much for one person.

**Comment by phlprcks** [comment]
> 
> 
> > I'm not sure if these changes are what @sinnaj-r meant by "tidying up the tests". I think he was more refering to these things
> > 
> > * factor out duplication
> > * remove conditional test logic
> > * write fixtures
> > * write helpers
> > * write custom asserts
> > * use child tests
> > * etc.
> > 
> > But I will defer to him on that.
> 
> In fact, I was originally concerned with the correct classification of the tests(-methods) into classes and categories.
> 
> However, the points you raised are still important - I would have associated them with Issue #134, but I can also understand if that would be too much for one person.

Indeed. @robertkirsten I assume you are dealing with most of it in #134 . How is that going?

**Comment by phlprcks** [comment]
Closing this one for clarification as the refactorings mentioned by @BenBals are supposed to happen with #134 by @robertkirsten (in case you need help please let us know).
