### ISSUE TITLE
Indicate that children can be searched through

### ISSUE THREAD

**Issue by BenBals** [hpi-swa-teaching/Algernon-Launcher#92]
In Algernon you can search through the children of a result. That's non-obvious. As a beginner I might not know about that feature and would like a visual hint.

# Acceptance Criteria
| Team | Client | Description |
|------|--------|-------------|
| :x: | :x: | Opening the child view shows a visual indication that you can search by typing |
| :x: | :x: | what visual to use is tbd |

**Comment by sinnaj-r** [comment]
I think a placeholder-text (also for the default "parent"-search) stating something like "Enter your Search-Term" would be nice

**Comment by BenBals** [comment]
Yes, but maybe greyed out or something while placing the cursor correctly.

Just having a blinking cursor might also be a starting point.

**Comment by phlprcks** [comment]
How to indicate that should be decided by the customer - let's ask him if he chooses this story
