### ISSUE TITLE
Algernon keeps position when resizing window

### ISSUE THREAD

**Issue by sinnaj-r** [hpi-swa-teaching/Algernon-Launcher#93]
As a user I want Algernon to be opened within my view even if I changed the monitor resolution in order to see Algernon properly.

More info:
When I open Algernon on an ultrawilde monitor and than on a narrow monitor algernon is out of view. We should reset the repositioning when the resolution of squeak changes.

# Acceptance Criteria
| Team | Customer | Title |
|------|----------|-------|
| :x: | :heavy_check_mark: | When I switch to another resolution, a new Algernon opens within my view |

**Comment by BenBals** [comment]
What you are observing is the behavior of all of Squeak.

**Comment by sinnaj-r** [comment]
That's true, but other squeak-windows can be just closed and opened again; getting Algernon to show up again is far more difficult for the user. 
Also I think it would be quite easy to just remember the resolution and reset the location when it was changed since the last Algernon activation.

**Comment by BenBals** [comment]
That's true, but I don't think it's a bug. I think we should estimate it and "bill" the client for it as it is a new feature.

**Comment by phlprcks** [comment]
> 
> 
> That's true, but I don't think it's a bug. I think we should estimate it and "bill" the client for it as it is a new feature.

Same opinion. I edited the description accordingly.
