### ISSUE TITLE
The Text-Input should "scroll" with the cursor

### ISSUE THREAD

**Issue by sinnaj-r** [hpi-swa-teaching/Algernon-Launcher#94]
As a user I want to see the entered text also for a long string (e.g.  e.g. a Smalltalk-Expression.) in the Input Field in order to navigate and check my typed letters in the input field.

Additional Info:
Currently the textfield doesn't show the text around the current cursor position, but only the first words (which are then truncated).

# Acceptance Criteria
| Team | Customer | Title |
|------|----------|-------|
| :x: | :x: | Text around the curser is shown in the input field |
| :x: | :x: | the text "moves/scrolls" when text that exceeds the field size is entered |
| :x: | :x: | the text "moves/scrolls" according to the cursor position (e.g. on navigating with the cursor|

**Comment by niklasmohrin** [comment]
I dug around the image a bit and I think that we should try using the ToolBuilder and do something similar to the model `SearchBar` (the search bar from the top right corner of the image). The `buildWith:` method doesn't seems too complicated either

Alternatively, we could take a look at `TextEditor`, which seems to be the class implementing the normal text fields (`SmalltalkEditor` inherits from that and this is what the editor in the browser window is using as far as I can tell)

Edit:

The first approach yields a nice box that scrolls with the input. I think that hooking up ALGCore with the contents of the input should not be too hard, I don't know how the `keyStroke` logic from the original input field should be built. The tool builder only builds the morph which wants to do all the keyboard things itself. Maybe we could add another class that holds the model and has the built view as a submorph? This way, we could probably stay fully backward compatible with the existing input field by forwarding the needed messages to either view or model and also handle key strokes on our own before passing them to the view.

I have pushed my current work to

https://github.com/hpi-swa-teaching/Algernon-Launcher/tree/scrolling-input-field 

Naturally, nothing works when checkout out this branch yet, but it's a start :laughing:
